import 'package:fancad_core/fancad_core.dart';

/// Generates `fancad.d.ts`.
///
/// This file is the plugin API's contract in the only form that helps the two
/// audiences that matter: an editor gives a human completion, and a language
/// model gets the exact signatures instead of inventing plausible ones. The
/// command list is generated from the live registry, so it cannot drift.
String buildTypeDeclarations({
  required Iterable<CommandDescriptor> commands,
  String hostVersion = '0.1.0',
}) {
  final buffer = StringBuffer();
  buffer.writeln('// Generated by FanCAD $hostVersion. Do not edit.');
  buffer.writeln('// Describes the `fancad` global available to plugins.');
  buffer.writeln();
  buffer.writeln(_staticDeclarations);
  buffer.writeln();
  buffer.writeln('/** Every command registered in this build. */');
  buffer.writeln('declare type FanCadCommandId =');
  final sorted = commands.map((command) => command.id).toList()..sort();
  if (sorted.isEmpty) {
    buffer.writeln('  string;');
  } else {
    for (var i = 0; i < sorted.length; i++) {
      final separator = i == sorted.length - 1 ? ';' : '';
      buffer.writeln("  | '${sorted[i]}'$separator");
    }
  }
  buffer.writeln();
  buffer.writeln('declare namespace FanCadCommands {');
  for (final command in commands.toList()
    ..sort((a, b) => a.id.compareTo(b.id))) {
    buffer.writeln('  /**');
    buffer.writeln('   * ${command.title}');
    if (command.description.isNotEmpty) {
      buffer.writeln('   *');
      for (final line in _wrap(command.description, 72)) {
        buffer.writeln('   * $line');
      }
    }
    if (command.aliases.isNotEmpty) {
      buffer.writeln('   *');
      buffer.writeln('   * Aliases: ${command.aliases.join(', ')}');
    }
    buffer.writeln('   */');
    buffer.writeln('  interface ${_typeNameOf(command.id)} {');
    for (final param in command.params) {
      if (param.description.isNotEmpty) {
        buffer.writeln('    /** ${param.description} */');
      }
      final optional = param.required ? '' : '?';
      buffer.writeln(
        '    ${_safeKey(param.name)}$optional: ${_tsTypeOf(param)};',
      );
    }
    buffer.writeln('  }');
  }
  buffer.writeln('}');
  return buffer.toString();
}

String _tsTypeOf(ParamSpec param) => switch (param.type) {
  ParamType.text || ParamType.layer || ParamType.block => 'string',
  ParamType.number || ParamType.distance || ParamType.angle => 'number',
  ParamType.integer || ParamType.entity => 'number',
  ParamType.boolean => 'boolean',
  ParamType.point => 'Point',
  ParamType.selection => 'number[]',
  ParamType.choice =>
    param.options.map((option) => "'$option'").join(' | '),
  ParamType.json => 'Record<string, unknown>',
  ParamType.points => 'Point[]',
};

/// Turns `draw.line` into `DrawLine`.
String _typeNameOf(String commandId) => commandId
    .split(RegExp(r'[.\-_]'))
    .where((part) => part.isNotEmpty)
    .map((part) => part[0].toUpperCase() + part.substring(1))
    .join();

String _safeKey(String name) =>
    RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(name) ? name : "'$name'";

List<String> _wrap(String text, int width) {
  final words = text.split(RegExp(r'\s+'));
  final lines = <String>[];
  var current = StringBuffer();
  for (final word in words) {
    if (current.isNotEmpty && current.length + word.length + 1 > width) {
      lines.add(current.toString());
      current = StringBuffer();
    }
    if (current.isNotEmpty) current.write(' ');
    current.write(word);
  }
  if (current.isNotEmpty) lines.add(current.toString());
  return lines;
}

const String _staticDeclarations = r'''
/** A model-space coordinate as [x, y], in drawing units. */
declare type Point = [number, number] | { x: number; y: number };

/** An axis-aligned box as [minX, minY, maxX, maxY]. */
declare type Bounds = [number, number, number, number];

declare interface Disposable {
  dispose(): void | Promise<void>;
}

declare interface EntityProps {
  /** Layer name. Defaults to the current layer. */
  layer?: string;
  /** ACI index, `"bylayer"`, `"byblock"`, or `"#rrggbb"`. */
  color?: number | string;
  lineType?: string;
  lineWeight?: number;
}

declare interface EntitySummary {
  id: number;
  kind: string;
  layer: string;
  bounds: Bounds;
}

declare interface EntityDetail extends EntitySummary {
  start?: [number, number];
  end?: [number, number];
  center?: [number, number];
  radius?: number;
  startAngle?: number;
  endAngle?: number;
  points?: [number, number][];
  closed?: boolean;
  position?: [number, number];
  text?: string;
  height?: number;
}

declare interface DrawingSummary {
  entityCount: number;
  layers: string[];
  currentLayer: string;
  byKind: Record<string, number>;
  extents?: Bounds;
}

declare interface QueryFilter {
  layer?: string;
  kinds?: string | string[];
  /** Only entities whose bounds meet this box. */
  window?: Bounds;
  /** Defaults to 500. */
  limit?: number;
}

declare interface LayerInfo {
  name: string;
  visible: boolean;
  locked: boolean;
  frozen: boolean;
}

declare interface CommandOutcome {
  status: 'ok' | 'cancelled' | 'failed';
  message?: string;
  data?: Record<string, unknown>;
  change?: {
    label: string;
    summary: string;
    added: number[];
    removed: number[];
    modified: number[];
  };
}

declare interface EditResult {
  applied: boolean;
  /** Ids of entities created by this edit, in operation order. */
  created: number[];
  /** Ids skipped because their layer is locked. */
  blockedByLockedLayer?: string[];
  label?: string;
}

/**
 * Collects operations and applies them as one undoable change.
 *
 * Prefer this over one call per entity: the user should undo what your command
 * did, not one three-hundredth of it.
 */
declare interface EditBuilder {
  line(from: Point, to: Point, props?: EntityProps): EditBuilder;
  polyline(
    points: Point[],
    options?: { closed?: boolean; props?: EntityProps }
  ): EditBuilder;
  circle(center: Point, radius: number, props?: EntityProps): EditBuilder;
  arc(
    center: Point,
    radius: number,
    startAngle: number,
    endAngle: number,
    props?: EntityProps
  ): EditBuilder;
  text(
    position: Point,
    value: string,
    options?: { height?: number; rotation?: number; props?: EntityProps }
  ): EditBuilder;
  erase(ids: number | number[]): EditBuilder;
  move(ids: number | number[], delta: Point): EditBuilder;
  setProps(ids: number | number[], props: EntityProps): EditBuilder;
  commit(): Promise<EditResult>;
}

declare interface PromptSpec {
  kind: 'text' | 'number' | 'point' | 'selection' | 'confirm' | 'choice';
  message: string;
  options?: string[];
  defaultValue?: unknown;
}

declare interface FanCadApi {
  /** This plugin's id, from its manifest. */
  readonly id: string;
  readonly version: string;
  readonly hostVersion: string;
  /** Permissions granted by the manifest. */
  readonly permissions: string[];

  readonly commands: {
    /**
     * Registers the handler for a command declared in `contributes.commands`.
     * Registering a command the manifest does not declare leaves it
     * unreachable from the palette.
     */
    register(
      id: string,
      handler: (args: Record<string, unknown>) => unknown
    ): Disposable;
    /** Runs any command, built-in or contributed. Needs `commands`. */
    execute(id: string, args?: Record<string, unknown>): Promise<CommandOutcome>;
    list(): Promise<{ commands: unknown[] }>;
  };

  readonly document: {
    /** Counts and extents, cheap enough to call freely. */
    summary(): Promise<DrawingSummary>;
    /** Filtered retrieval. Prefer this over reading the whole drawing. */
    query(filter?: QueryFilter): Promise<{
      entities: EntitySummary[];
      truncated: boolean;
    }>;
    entity(id: number): Promise<EntityDetail>;
    layers(): Promise<{ current: string; layers: LayerInfo[] }>;
    /** Applies raw operations. Needs `document.write`. */
    edit(label: string, operations: unknown[]): Promise<EditResult>;
    /** The readable way to build an edit. Needs `document.write`. */
    beginEdit(label: string): EditBuilder;
  };

  readonly selection: {
    get(): Promise<{ ids: number[] }>;
    set(ids: number | number[]): Promise<{ ids: number[] }>;
    clear(): Promise<{ ids: number[] }>;
  };

  readonly window: {
    showMessage(message: string, options?: { error?: boolean }): Promise<void>;
    showError(message: string): Promise<void>;
    /** Asks the user for a value. Needs `ui`. */
    prompt(spec: PromptSpec): Promise<unknown>;
  };

  readonly storage: {
    get<T>(key: string, fallback?: T): Promise<T>;
    /** Needs `file.write`. */
    set(key: string, value: unknown): Promise<void>;
  };

  readonly events: {
    /**
     * Known events: `document.changed`, `document.opened`,
     * `selection.changed`, `layer.changed`.
     */
    on(name: string, handler: (payload: Record<string, unknown>) => unknown):
      Disposable;
  };

  readonly geometry: {
    point(x: number | Point, y?: number): [number, number];
    distance(a: Point, b: Point): number;
    /** Radians, measured counter-clockwise from the positive X axis. */
    angle(a: Point, b: Point): number;
    polar(origin: Point, angle: number, distance: number): [number, number];
    midpoint(a: Point, b: Point): [number, number];
    degrees(radians: number): number;
    radians(degrees: number): number;
  };
}

declare const fancad: FanCadApi;

/** Optional. Called once after the entry point is evaluated. */
declare function activate(api: FanCadApi): void | Promise<void>;

/** Optional. Called before the plugin is unloaded. */
declare function deactivate(): void | Promise<void>;
''';
