// Generated by FanCAD 0.1.0. Regenerated at runtime by `plugins.typings`.
// Describes the `fancad` global available to plugins.

/** A model-space coordinate as [x, y], in drawing units. */
declare type Point = [number, number] | { x: number; y: number };

/** An axis-aligned box as [minX, minY, maxX, maxY]. */
declare type Bounds = [number, number, number, number];

declare interface Disposable {
  dispose(): void | Promise<void>;
}

declare interface EntityProps {
  /** Layer name. Defaults to the current layer. */
  layer?: string;
  /** ACI index, `"bylayer"`, `"byblock"`, or `"#rrggbb"`. */
  color?: number | string;
  lineType?: string;
  lineWeight?: number;
}

declare interface EntitySummary {
  id: number;
  kind: string;
  layer: string;
  bounds: Bounds;
}

declare interface EntityDetail extends EntitySummary {
  start?: [number, number];
  end?: [number, number];
  center?: [number, number];
  radius?: number;
  startAngle?: number;
  endAngle?: number;
  points?: [number, number][];
  closed?: boolean;
  position?: [number, number];
  text?: string;
  height?: number;
}

declare interface DrawingSummary {
  entityCount: number;
  layers: string[];
  currentLayer: string;
  byKind: Record<string, number>;
  extents?: Bounds;
}

declare interface QueryFilter {
  layer?: string;
  kinds?: string | string[];
  /** Only entities whose bounds meet this box. */
  window?: Bounds;
  /** Defaults to 500. */
  limit?: number;
}

declare interface LayerInfo {
  name: string;
  visible: boolean;
  locked: boolean;
  frozen: boolean;
}

declare interface CommandOutcome {
  status: 'ok' | 'cancelled' | 'failed';
  message?: string;
  data?: Record<string, unknown>;
  change?: {
    label: string;
    summary: string;
    added: number[];
    removed: number[];
    modified: number[];
  };
}

declare interface EditResult {
  applied: boolean;
  /** Ids of entities created by this edit, in operation order. */
  created: number[];
  /** Ids skipped because their layer is locked. */
  blockedByLockedLayer?: string[];
  label?: string;
}

/**
 * Collects operations and applies them as one undoable change.
 *
 * Prefer this over one call per entity: the user should undo what your command
 * did, not one three-hundredth of it.
 */
declare interface EditBuilder {
  line(from: Point, to: Point, props?: EntityProps): EditBuilder;
  polyline(
    points: Point[],
    options?: { closed?: boolean; props?: EntityProps }
  ): EditBuilder;
  circle(center: Point, radius: number, props?: EntityProps): EditBuilder;
  arc(
    center: Point,
    radius: number,
    startAngle: number,
    endAngle: number,
    props?: EntityProps
  ): EditBuilder;
  text(
    position: Point,
    value: string,
    options?: { height?: number; rotation?: number; props?: EntityProps }
  ): EditBuilder;
  erase(ids: number | number[]): EditBuilder;
  move(ids: number | number[], delta: Point): EditBuilder;
  setProps(ids: number | number[], props: EntityProps): EditBuilder;
  commit(): Promise<EditResult>;
}

declare interface PromptSpec {
  kind: 'text' | 'number' | 'point' | 'selection' | 'confirm' | 'choice';
  message: string;
  options?: string[];
  defaultValue?: unknown;
}

declare interface FanCadApi {
  /** This plugin's id, from its manifest. */
  readonly id: string;
  readonly version: string;
  readonly hostVersion: string;
  /** Permissions granted by the manifest. */
  readonly permissions: string[];

  readonly commands: {
    /**
     * Registers the handler for a command declared in `contributes.commands`.
     * Registering a command the manifest does not declare leaves it
     * unreachable from the palette.
     */
    register(
      id: string,
      handler: (args: Record<string, unknown>) => unknown
    ): Disposable;
    /** Runs any command, built-in or contributed. Needs `commands`. */
    execute(id: string, args?: Record<string, unknown>): Promise<CommandOutcome>;
    list(): Promise<{ commands: unknown[] }>;
  };

  readonly document: {
    /** Counts and extents, cheap enough to call freely. */
    summary(): Promise<DrawingSummary>;
    /** Filtered retrieval. Prefer this over reading the whole drawing. */
    query(filter?: QueryFilter): Promise<{
      entities: EntitySummary[];
      truncated: boolean;
    }>;
    entity(id: number): Promise<EntityDetail>;
    layers(): Promise<{ current: string; layers: LayerInfo[] }>;
    /** Applies raw operations. Needs `document.write`. */
    edit(label: string, operations: unknown[]): Promise<EditResult>;
    /** The readable way to build an edit. Needs `document.write`. */
    beginEdit(label: string): EditBuilder;
  };

  readonly selection: {
    get(): Promise<{ ids: number[] }>;
    set(ids: number | number[]): Promise<{ ids: number[] }>;
    clear(): Promise<{ ids: number[] }>;
  };

  readonly window: {
    showMessage(message: string, options?: { error?: boolean }): Promise<void>;
    showError(message: string): Promise<void>;
    /** Asks the user for a value. Needs `ui`. */
    prompt(spec: PromptSpec): Promise<unknown>;
  };

  readonly storage: {
    get<T>(key: string, fallback?: T): Promise<T>;
    /** Needs `file.write`. */
    set(key: string, value: unknown): Promise<void>;
  };

  readonly events: {
    /**
     * Known events: `document.changed`, `document.opened`,
     * `selection.changed`, `layer.changed`.
     */
    on(name: string, handler: (payload: Record<string, unknown>) => unknown):
      Disposable;
  };

  readonly geometry: {
    point(x: number | Point, y?: number): [number, number];
    distance(a: Point, b: Point): number;
    /** Radians, measured counter-clockwise from the positive X axis. */
    angle(a: Point, b: Point): number;
    polar(origin: Point, angle: number, distance: number): [number, number];
    midpoint(a: Point, b: Point): [number, number];
    degrees(radians: number): number;
    radians(degrees: number): number;
  };
}

declare const fancad: FanCadApi;

/** Optional. Called once after the entry point is evaluated. */
declare function activate(api: FanCadApi): void | Promise<void>;

/** Optional. Called before the plugin is unloaded. */
declare function deactivate(): void | Promise<void>;

/** Every command registered in this build. Regenerated live by plugins.typings. */
declare type FanCadCommandId = string;
